import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ScoreHistory from './components/ScoreHistory';
import Players from "./components/Players";
import Table from "./table";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Football Tracker APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1>Football tracker App</h1>
        {/* score History */}
      <ScoreHistory />
        {/*  table */}
      {/*<LeagueTable />*/}

        {/*  player in a team */}
        <Players />
      {/*<Players team={'Arsenal'}/>*/}
        <Table/>

    </div>
  )
}
